"Advertising":"",
"Car & Truck Expenses":"",
"Contractors":"",
"Education and Training":"",
"Employee Benefits":"",
"Meals & Entertainment":"",
"Office Expenses & Postage":"",
"Other Expenses":"",
"Personal":"",
"Professional Services":"",
"Rent or Lease":"",
"Supplies":"",
"Travel":"",
"Utilities":"",